<a href="https://colab.research.google.com/github/Tarun-23113/My_Python_Projects/blob/master/Pandas_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/netflix_titles.csv")

In [60]:
# Task 1: Show first and last 5 rows of the dataset

display(df.head(5))
display(df.tail(5))

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [61]:
# Task 2: display column names, data types, and shape of the dataset

display(df.columns)
display(df.dtypes)
display(df.shape)

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

(8807, 12)

In [62]:
# Task 3: Use describe() and info() to get summary stats

display(df.describe())

display(df.info())

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

None

In [63]:
# Task 4: Find how many movies vs TV shows (value_counts on 'type')

df['type'].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [64]:
# Task 5: Use loc and iloc to display:
#         - 10 random movies
#         - 5 entries with 'TV Show' type and 'Country' = 'India'

display(df[df['type'] == 'Movie'].sample(10))

display(df.query("type == 'TV Show' and country == 'India'").head(5))

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
6846,s6847,Movie,Ghost Pain,"Kazuchika Kise, Masahiko Murata","Maaya Sakamoto, Ikkyu Juku, Kenichirou Matsuda...",Japan,"February 24, 2019",2013,TV-MA,58 min,"Action & Adventure, Anime Features, Internatio...","World War IV is over, but a bomb has gone off ..."
4456,s4457,Movie,Raja Natwarlal,Kunal Deshmukh,"Emraan Hashmi, Humaima Malik, Paresh Rawal, Ka...",India,"November 1, 2018",2014,TV-14,131 min,"Dramas, International Movies, Thrillers",A small-time con man assembles a team to help ...
5106,s5107,Movie,Bibi & Tina: Tohuwabohu Total,Detlev Buck,"Lina Larissa Strahl, Lisa-Marie Koroll, Louis ...",Germany,"December 27, 2017",2017,TV-14,106 min,"Children & Family Movies, Music & Musicals",Teen witch Bibi and her pal Tina return to the...
8136,s8137,Movie,Swami,Basu Chatterjee,"Shabana Azmi, Girish Karnad, Vikram, Dheeraj K...",India,"December 31, 2019",1977,TV-PG,123 min,"Dramas, Independent Movies, International Movies","After she enters into an arranged marriage, a ..."
7458,s7459,Movie,Minnaminugu the FireFly,Anil Thomas,"Surabhi Lakshmi, Krishnan Balakrishnan, Rebecc...",India,"August 1, 2018",2017,TV-14,128 min,"Dramas, International Movies",A nameless widow juggles multiple jobs to supp...
1000,s1001,Movie,Wild Dog,Ahishor Solomon,"Nagarjuna Akkineni, Dia Mirza, Saiyami Kher, A...",NaN,"April 22, 2021",2020,TV-MA,126 min,"Action & Adventure, International Movies",A brash but brilliant Indian intelligence agen...
8522,s8523,Movie,The Super,Stephan Rick,"Patrick John Flueger, Val Kilmer, Louisa Kraus...",United States,"February 16, 2019",2017,R,89 min,Horror Movies,When an ex-cop becomes a superintendent of an ...
6990,s6991,Movie,Honey 2,Bille Woodruff,"Kat Graham, Mario Lopez, Audrina Patridge, Sey...",United States,"October 1, 2019",2011,PG-13,111 min,"Dramas, Romantic Movies",Determined to prove herself as a street dancer...
96,s97,Movie,If I Leave Here Tomorrow: A Film About Lynyrd ...,Stephen Kijak,"Ronnie Van Zandt, Gary Rossington, Allen Colli...",United States,"September 7, 2021",2018,TV-MA,97 min,"Documentaries, Music & Musicals","Using interviews and archival footage, this do..."
7895,s7896,Movie,Rounders,John Dahl,"Matt Damon, Edward Norton, John Turturro, Gret...",United States,"November 1, 2019",1998,R,121 min,Dramas,"A law student befriends and ""befoes"" a fellow ..."

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
39,s40,TV Show,Chhota Bheem,NaN,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",India,"September 16, 2021",2021,TV-Y7,3 Seasons,Kids' TV,"A brave, energetic little boy with superhuman ..."
50,s51,TV Show,Dharmakshetra,NaN,"Kashmira Irani, Chandan Anand, Dinesh Mehta, A...",India,"September 15, 2021",2014,TV-PG,1 Season,"International TV Shows, TV Dramas, TV Sci-Fi &...","After the ancient Great War, the god Chitragup..."
66,s67,TV Show,Raja Rasoi Aur Anya Kahaniyan,NaN,NaN,India,"September 15, 2021",2014,TV-G,1 Season,"Docuseries, International TV Shows",Explore the history and flavors of regional In...
69,s70,TV Show,Stories by Rabindranath Tagore,NaN,NaN,India,"September 15, 2021",2015,TV-PG,1 Season,"International TV Shows, TV Dramas",The writings of Nobel Prize winner Rabindranat...

In [65]:
# Task 6: Check missing values in all columns (isnull().sum())

df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [66]:
# Task 7: Fill missing 'director' values with "Unknown"
#         Fill missing 'country' values with "Unspecified"

df['director'].fillna("Unknown")
df['country'].fillna("Unspecified")

0       United States
1        South Africa
2         Unspecified
3         Unspecified
4               India
            ...
8802    United States
8803      Unspecified
8804    United States
8805    United States
8806            India
Name: country, Length: 8807, dtype: object

In [67]:
# Task 8: Drop rows where 'title' or 'type' is missing

df.dropna(subset=['title', 'type'], inplace=True)

In [68]:
# Task 9: Remove duplicate rows (if any)

df.drop_duplicates(inplace=True)

In [69]:
# Task 10: Extract year from 'date_added' and store in a new column 'year_added'
#          Hint: Convert 'date_added' to datetime using pd.to_datetime()

df['year_added'] = df['date_added'].str.extract(r'([^,]+)$')

In [70]:
# Task 11: Rename 'listed_in' column to 'genre' for clarity

df.rename(columns={'listed_in':'genre'}, inplace=True)

In [76]:
# Task 12: Sort dataset by 'release_year' descending and show top 10 oldest titles

df.sort_values('release_year', ascending=False)['title'].tail(10)

1331                 Five Came Back: The Reference Films
8419    The Memphis Belle: A Story of a\nFlying Fortress
8436                                   The Negro Soldier
8640                                    Tunisian Victory
8763                     WWII: Report from the Aleutians
8739                  Why We Fight: The Battle of Russia
8660       Undercover: How to Operate Behind Enemy Lines
7790                                      Prelude to War
8205                                The Battle of Midway
4250                   Pioneers: First Women Filmmakers*
Name: title, dtype: object

In [80]:
# Task 13: Group by 'type' and 'release_year' → count how many titles per year

df.groupby(['release_year', 'type'])['title'].count()

release_year  type
1925          TV Show      1
1942          Movie        2
1943          Movie        3
1944          Movie        3
1945          Movie        3
                        ...
2019          TV Show    397
2020          Movie      517
              TV Show    436
2021          Movie      277
              TV Show    315
Name: title, Length: 119, dtype: int64

In [82]:
# Task 14: Create a new column 'is_in_India' → True if 'country' contains 'India'

df['is_in_India'] = df['country'] == 'India'
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genre,description,year_added,is_in_India
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021,False
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021,False
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021,False
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021,False
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",2019,False
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",2019,False
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,2019,False
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",2020,False
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019,True

In [85]:
# Task 15: Use pd.cut() to bin 'release_year' into 5 intervals (like decades)

df['Era'] = pd.cut(df['release_year'], bins=5, labels=['Beginning', 'Experimental', 'Golden', 'Saturated', 'Cinephiles'])
df[30:50]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genre,description,year_added,is_in_India,Era
30,s31,Movie,Ankahi Kahaniya,"Ashwiny Iyer Tiwari, Abhishek Chaubey, Saket C...","Abhishek Banerjee, Rinku Rajguru, Delzad Hiwal...",NaN,"September 17, 2021",2021,TV-14,111 min,"Dramas, Independent Movies, International Movies","As big city life buzzes around them, lonely so...",2021,False,Cinephiles
31,s32,TV Show,Chicago Party Aunt,NaN,"Lauren Ash, Rory O'Malley, RuPaul Charles, Jil...",NaN,"September 17, 2021",2021,TV-MA,1 Season,TV Comedies,Chicago Party Aunt Diane is an idolized troubl...,2021,False,Cinephiles
32,s33,TV Show,Sex Education,NaN,"Asa Butterfield, Gillian Anderson, Ncuti Gatwa...",United Kingdom,"September 17, 2021",2020,TV-MA,3 Seasons,"British TV Shows, International TV Shows, TV C...",Insecure Otis has all the answers when it come...,2021,False,Cinephiles
33,s34,TV Show,Squid Game,NaN,"Lee Jung-jae, Park Hae-soo, Wi Ha-jun, Oh Youn...",NaN,"September 17, 2021",2021,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Thrillers",Hundreds of cash-strapped players accept a str...,2021,False,Cinephiles
34,s35,TV Show,Tayo and Little Wizards,NaN,"Dami Lee, Jason Lee, Bommie Catherine Han, Jen...",NaN,"September 17, 2021",2020,TV-Y7,1 Season,Kids' TV,Tayo speeds into an adventure when his friends...,2021,False,Cinephiles
35,s36,Movie,The Father Who Moves Mountains,Daniel Sandu,"Adrian Titieni, Elena Purea, Judith State, Val...",NaN,"September 17, 2021",2021,TV-MA,110 min,"Dramas, International Movies, Thrillers",When his son goes missing during a snowy hike ...,2021,False,Cinephiles
36,s37,Movie,The Stronghold,Cédric Jimenez,"Gilles Lellouche, Karim Leklou, François Civil...",NaN,"September 17, 2021",2021,TV-MA,105 min,"Action & Adventure, Dramas, International Movies","Tired of the small-time grind, three Marseille...",2021,False,Cinephiles
37,s38,TV Show,Angry Birds,NaN,"Antti Pääkkönen, Heljä Heikkinen, Lynne Guagli...",Finland,"September 16, 2021",2018,TV-Y7,1 Season,"Kids' TV, TV Comedies","Birds Red, Chuck and their feathered friends h...",2021,False,Cinephiles
38,s39,Movie,Birth of the Dragon,George Nolfi,"Billy Magnussen, Ron Yuan, Qu Jingjing, Terry ...","China, Canada, United States","September 16, 2021",2017,PG-13,96 min,"Action & Adventure, Dramas",A young Bruce Lee angers kung fu traditionalis...,2021,False,Cinephiles
39,s40,TV Show,Chhota Bheem,NaN,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",India,"September 16, 2021",2021,TV-Y7,3 Seasons,Kids' TV,"A brave, energetic little boy with superhuman ...",2021,True,Cinephiles
40,s41,TV Show,He-Man and the Masters of the Universe,NaN,"Yuri Lowenthal, Kimberly Brooks, Antony Del Ri...",United States,"September 16, 2021",2021,TV-Y7,1 Season,"Kids' TV, TV Sci-Fi & Fantasy",Mighty teen Adam and his heroic squad of misfi...,2021,False,Cinephiles
41,s42,Movie,Jaws,Steven Spielberg,"Roy Scheider, Robert Shaw, Richard Dreyfuss, L...",United States,"September 16, 2021",1975,PG,124 min,"Action & Adventure, Classic Movies, Dramas",When an insatiable great white shark terrorize...,2021,False,Golden
42,s43,Movie,Jaws 2,Jeannot Szwarc,"Roy Scheider, Lorraine Gary, Murray Hamilton, ...",United States,"September 16, 2021",1978,PG,116 min,"Dramas, Horror Movies, Thrillers",Four years after the last deadly shark attacks...,2021,False,Golden
43,s44,Movie,Jaws 3,Joe Alves,"Dennis Quaid, Bess Armstrong, Simon MacCorkind...",United States,"September 16, 2021",1983,PG,98 min,"Action & Adventure, Horror Movies, Thrillers",After the staff of a marine theme park try to ...,2021,False,Saturated
44,s45,Movie,Jaws: The Revenge,Joseph Sargent,"Lorraine Gary, Lance Guest, Mario Van Peebles,...",United States,"September 16, 2021",1987,PG-13,91 min,"Action & Adventure, Horror Movies, Thrillers","After another deadly shark attack, Ellen Brody...",2021,False,Saturated
45,s46,Movie,My Heroes Were Cowboys,Tyler Greco,NaN,NaN,"September 16, 2021",2021,PG,23 min,Documentaries,Robin Wiltshire's painful childhood was rescue...,2021,False,Cinephiles
46,s47,Movie,Safe House,Daniel Espinosa,"Denzel Washington, Ryan Reynolds, Vera Farmiga...","South Africa, United States, Japan","September 16, 2021",2012,R,115 min,Action & Adventure,Young CIA operative Matt Weston must get a dan...,2021,False,Cinephiles
47,s48,TV Show,The Smart Money Woman,Bunmi Ajakaiye,"Osas Ighodaro, Ini Dima-Okojie, Kemi Lala Akin...",NaN,"September 16, 2021",2020,TV-MA,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Five glamorous millennials strive for success ...,2021,False,Cinephiles
48,s49,Movie,Training Day,Antoine Fuqua,"Denzel Washington, Ethan Hawke, Scott Glenn, T...",United States,"September 16, 2021",2001,R,122 min,"Dramas, Thrillers",A rookie cop with one day to prove himself to ...,2021,False,Saturated
49,s50,TV Show,Castle and Castle,NaN,"Richard Mofe-Damijo, Dakore Akande, Bimbo Manu...",Nigeria,"September 15, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas","A pair of high-powered, successful lawyers fin...",2021,False,Cinephiles

In [88]:
# Task 16: Use str.extract() to extract the first genre from the 'genre' column

df['genre'].str.extract(r'^([^,&]+)')

                           0
0              Documentaries
1     International TV Shows
2             Crime TV Shows
3                 Docuseries
4     International TV Shows
...                      ...
8802             Cult Movies
8803                Kids' TV
8804                Comedies
8805               Children
8806                  Dramas

[8807 rows x 1 columns]

In [103]:
# Task 17: Count top 5 directors with most titles

df.groupby('director')['title'].count().sort_values(ascending=False).head(5)

director
Rajiv Chilaka             19
Raúl Campos, Jan Suter    18
Suhas Kadav               16
Marcus Raboy              16
Jay Karas                 14
Name: title, dtype: int64

In [114]:
# Task 18: Pivot Table → Show count of Movies/TV Shows by country (rows) and type (columns)

pd.pivot_table(df, 'title', 'country', 'type', aggfunc='count')

type                                                Movie  TV Show
country
, France, Algeria                                     1.0      NaN
, South Korea                                         NaN      1.0
Argentina                                            38.0     18.0
Argentina, Brazil, France, Poland, Germany, Den...    1.0      NaN
Argentina, Chile                                      2.0      NaN
...                                                   ...      ...
Venezuela                                             1.0      NaN
Venezuela, Colombia                                   1.0      NaN
Vietnam                                               7.0      NaN
West Germany                                          1.0      NaN
Zimbabwe                                              1.0      NaN

[748 rows x 2 columns]

In [126]:
# Task 19: Use groupby().transform() to create column:
#          'title_count_by_country' = number of titles per country

df['title_count_by_country'] = df.groupby('country')['title'].transform('count')
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genre,description,year_added,is_in_India,Era,title_count_by_country
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021,False,Cinephiles,2818.0
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021,False,Cinephiles,30.0
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021,False,Cinephiles,NaN
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021,False,Cinephiles,NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021,True,Cinephiles,972.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",2019,False,Cinephiles,2818.0
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",2019,False,Cinephiles,NaN
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,2019,False,Cinephiles,2818.0
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",2020,False,Cinephiles,2818.0
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019,True,Cinephiles,972.0

In [130]:
# Task 20: Use melt() to reshape 'duration' and 'rating' into one column

pd.melt(df, id_vars='title', value_vars=['duration', 'rating'], var_name='D_R', value_name='Result')

                       title       D_R     Result
0       Dick Johnson Is Dead  duration     90 min
1              Blood & Water  duration  2 Seasons
2                  Ganglands  duration   1 Season
3      Jailbirds New Orleans  duration   1 Season
4               Kota Factory  duration  2 Seasons
...                      ...       ...        ...
17609                 Zodiac    rating          R
17610            Zombie Dumb    rating      TV-Y7
17611             Zombieland    rating          R
17612                   Zoom    rating         PG
17613                 Zubaan    rating      TV-14

[17614 rows x 3 columns]

In [131]:
# Goal: Generate insights about Netflix content trends

In [137]:
# Step 1: Clean 'duration' column (e.g. extract minutes or seasons)

df['duration_length'] = df['duration'].str.extract(r'^([^\s]+)')
df['duration_type'] = df['duration'].str.extract(r'^[0-9]+\s([A-z]+)')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genre,description,year_added,is_in_India,Era,title_count_by_country,duration_length,duration_type
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021,False,Cinephiles,2818.0,90,min
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021,False,Cinephiles,30.0,2,Seasons
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021,False,Cinephiles,NaN,1,Season
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021,False,Cinephiles,NaN,1,Season
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021,True,Cinephiles,972.0,2,Seasons

In [154]:
# Step 2: Find top 10 countries with most Netflix content

df.groupby('country')['title'].count().sort_values(ascending=False).head(10)

country
United States     2818
India              972
United Kingdom     419
Japan              245
South Korea        199
Canada             181
Spain              145
France             124
Mexico             110
Egypt              106
Name: title, dtype: int64

In [161]:
# Step 3: Analyze most common genres globally

df.groupby('genre')['title'].count().sort_values(ascending=False).head(15)

genre
Dramas, International Movies                        362
Documentaries                                       359
Stand-Up Comedy                                     334
Comedies, Dramas, International Movies              274
Dramas, Independent Movies, International Movies    252
Kids' TV                                            220
Children & Family Movies                            215
Children & Family Movies, Comedies                  201
Documentaries, International Movies                 186
Dramas, International Movies, Romantic Movies       180
Comedies, International Movies                      176
Comedies, International Movies, Romantic Movies     152
Dramas                                              138
Dramas, International Movies, Thrillers             134
Action & Adventure, Dramas, International Movies    132
Name: title, dtype: int64

In [162]:
# Step 5: Save final DataFrame to 'netflix_cleaned.csv'

df.to_csv("/content/netflix_cleaned.csv")